import { headers } from 'next/headers';
import { resolveTenantFromHost } from '@/lib/utils/resolveTenantFromHost';
import { resolveTenantConfig } from '@/features/tenant/tenant.service';
import { computeTenantCssVars } from '@/features/tenant/tenantCssVars';
import { Providers } from './providers';
import './globals.scss';

export const metadata = {
  title: 'Welcome to DigiGold',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const host = headersList.get('host');
  const defaultTenant =
    process.env.NEXT_PUBLIC_DEFAULT_TENANT ?? 'aurelian-digital';
  const retailerCode = resolveTenantFromHost(host, defaultTenant);
  const tenantConfig = await resolveTenantConfig(retailerCode);

  // Inlined synchronously in the SSR HTML so there's no flash of default branding before
  // the client's theme-sync effect (Providers' TenantThemeSync) runs.
  const cssVars = computeTenantCssVars(tenantConfig)
    .map(([name, value]) => `${name}:${value}`)
    .join(';');

  return (
    <html lang="en">
      <head>
        <style
          id="tenant-theme-vars"
          dangerouslySetInnerHTML={{ __html: `:root{${cssVars}}` }}
        />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100..900;1,100..900&display=swap');
        </style>
      </head>
      <body>
        <Providers initialTenantConfig={tenantConfig}>{children}</Providers>
      </body>
    </html>
  );
}
