package env

const (
	app_ENV_KEY               = "APP_ENV"
	PORT_KEY                  = "PORT"
	MONGO_URL_KEY             = "MONGO_URL"
	MONGO_DB_NAME_KEY         = "MONGO_DB_NAME"
	ACCESS_TOKEN_KEY          = "ACCESS_TOKEN_KEY"
	REFRESH_TOKEN_KEY         = "REFRESH_TOKEN_KEY"
	FIREBASE_JSON_STRING_KEY  = "FIREBASE_JSON_STRING"
	FIREBASE_DATABASE_URL_KEY = "FIREBASE_DATABASE_URL"

	// REDIS KEYS
	REDIS_DB_HOST_KEY         = "REDIS_DB_HOST"
	REDIS_DB_PORT_KEY         = "REDIS_DB_PORT"
	REDIS_DB_PASSWORD_KEY     = "REDIS_DB_PASSWORD"
	REDIS_DB_USERNAME_KEY     = "REDIS_DB_USERNAME"
	REDIS_DB_DATABASE_KEY     = "REDIS_DB_DATABASE"
	REDIS_DEFAULT_KEY_KEY     = "REDIS_DEFAULT_KEY"
	REDIS_DEFAULT_CHANNEL_KEY = "REDIS_DEFAULT_CHANNEL"

	// SURREAL DB KEYS

	SURREAL_URL_KEY         = "SURREAL_URL"
	SURREAL_NAMESPACE_KEY   = "SURREAL_NAMESPACE"
	SURREAL_DB_NAME_KEY     = "SURREAL_DB_NAME"
	SURREAL_DB_USERNAME_KEY = "SURREAL_DB_USERNAME"
	SURREAL_DB_PASSWORD_KEY = "SURREAL_DB_PASSWORD"

	RequestTokenHeaderKey = "X-Api-Token"

	// MYSQL DB KEYS

	MYSQL_HOST_KEY     = "MYSQL_HOST"
	MYSQL_PORT_KEY     = "MYSQL_PORT"
	MYSQL_USERNAME_KEY = "MYSQL_USERNAME"
	MYSQL_PASSWORD_KEY = "MYSQL_PASSWORD"
	MYSQL_DATABASE_KEY = "MYSQL_DATABASE"

	// POSTGRESQL DB KEYS
	PG_HOST_KEY     = "PG_HOST"
	PG_PORT_KEY     = "PG_PORT"
	PG_USERNAME_KEY = "PG_USERNAME"
	PG_PASSWORD_KEY = "PG_PASSWORD"
	PG_DATABASE_KEY = "PG_DATABASE"
	PG_SCHEMA_KEY   = "PG_SCHEMA"

	// REQ HEADER KEY
	XApiToken = RequestTokenHeaderKey
)
