export const ROUTES = {
  login: '/login',
  otp: '/otp',
  profileSetup: '/profile-setup',
  home: '/home',
  passbook: '/vault/passbook',
  sip: '/invest/sip',
  jewelry: '/marketplace/jewelry',
  marketplace: '/marketplace',
  aboutUs: '/about-us',
  vaultSecurity: '/vault/security',
  privacyPolicy: '/privacy-policy',
  termsOfService: '/terms-of-service',
  helpCenter: '/help-center',
  contactSupport: '/contact-support',
} as const;
